"""5本の動画を、制度ごとの短い動画に分ける表。切る位置は字幕の切り替わりと音のすき間で決めた（秒）。
始まりは「次の話題の画面と声が出る直前」。乱入や場面の切り替えの途中は、どちらの短い動画にも入れないことがある。
make_clips.py が動画とポスターを書き出し、make_index.py がこの表から動画コーナーを作る。"""

FULL = {
    # key: (番号, 題名, 長さ秒, グループ)
    "kaisei1p": ("改正編1", "11月以降に変わるお金のルールTOP5", 72.6, "fy2026"),
    "kaisei2p": ("改正編2", "知らないと損する 2027年度の制度改正TOP5", 66.9, "fy2027"),
    "seido1p": ("制度編1", "三英傑の年金：60歳・65歳・75歳、いちばん損するのは？", 69.1, "always"),
    "seido2p": ("制度編2", "年金生活、捨てたら損する封筒ベスト5", 72.1, "always"),
    "seido3p": ("制度編3", "親の家の手すり、工事の前に申請しないと損", 66.4, "always"),
}

GROUPS = [
    ("fy2026", "2026年度の改正", "この冬〜3月"),
    ("fy2027", "2027年度の改正", "2027年4月〜"),
    ("always", "いつでも役立つ制度", "年金・介護"),
]

# who は 制度データ の札（all＝ほとんどの人）。status は 決定／法案。
CLIPS = [
    dict(id="k1-1", src="kaisei1p", start=0.0, end=20.07, poster=8.2, rank="5位・4位",
         title="防衛特別所得税・こどもNISA", when="2027年1月から", who=["all", "kosodate"],
         point="所得税に1%上乗せ。ただし復興税が1%下がるので、合計は今と同じ（そのぶん長く続く）。こどもNISAは0〜17歳も年60万円まで。",
         todo="こどもNISAの口座の受付は始まっています（時期は金融機関で違う）", items=["boei_tax", "kodomo_nisa"]),
    dict(id="k1-2", src="kaisei1p", start=21.50, end=30.77, poster=25.6, rank="3位",
         title="iDeCoの上限アップ", when="2026年12月分から", who=["kaishain", "jieigyo"],
         point="企業年金のない会社員は月2.3万円→6.2万円。自営業などは月6.8万円→7.5万円。",
         todo="掛金を上げたい人は自分で手続き（自動では変わりません）", items=["ideco_limit"]),
    dict(id="k1-3", src="kaisei1p", start=30.95, end=42.80, poster=33.4, rank="2位",
         title="市販薬に似た薬の負担増", when="2027年3月から", who=["iryo"],
         point="湿布・保湿剤・花粉症の薬など77成分。薬代の4分の1が上乗せで、3割負担なら約1.6倍。子どもや入院中の人などは対象外。",
         todo="よく使う薬が対象か、薬局や医師に聞く", items=["otc_ruiji"]),
    dict(id="k1-4", src="kaisei1p", start=42.80, end=56.04, poster=48.6, rank="1位",
         title="12月に税金が戻る（精算）", when="2026年12月", who=["kaishain", "part", "nenkin"],
         point="11月まで古い基準で引いた所得税を、12月にまとめて精算。会社員は年末調整、年金は12月の支払いで。",
         todo="年末調整の書類を出す。年の途中で辞めた人は確定申告", items=["nencho2026"]),

    dict(id="k2-1", src="kaisei2p", start=0.0, end=18.46, poster=8.6, rank="5位・4位",
         title="パートの社会保険・子育て支援金", when="2027年10月から・4月から", who=["part", "all"],
         point="週20時間以上なら、36人以上の会社でも年収に関係なく社会保険に入ります。子育て支援金は平均で月100円ほど上がります。",
         todo="勤め先の人数と、自分の働く時間を確かめる", items=["tekiyo36", "kosodate_shienkin"]),
    dict(id="k2-2", src="kaisei2p", start=19.85, end=30.87, poster=24.2, rank="3位",
         title="高額療養費の上限", when="2027年8月から", who=["iryo"],
         point="区分が細かくなり、収入が高いほど上限が上がります。70歳未満・年収約650〜770万円なら月約8.6万円→約11万円。",
         todo="自分の区分を確かめる", items=["kougaku_2027"]),
    dict(id="k2-3", src="kaisei2p", start=31.05, end=38.50, poster=33.2, rank="2位",
         title="働く人への新しい給付金", when="2027年度", who=["kaishain", "part", "jieigyo"], status="法案",
         point="働く中低所得の人に年1回。金額はまだ決まっていません。公金受取口座があれば申請なしで受け取れる仕組みです。",
         todo="公金受取口座を登録しておく", items=["shugyosha_shien"]),
    dict(id="k2-4", src="kaisei2p", start=38.50, end=50.84, poster=42.6, rank="1位",
         title="食料品の消費税が1%に", when="2027年4月から2年間", who=["all"], status="法案",
         point="食料品の消費税が8%→1%に。ただし店内で食べると10%のまま。お酒も対象外です。",
         todo="法律が成立したかを確かめる", items=["shokuhin_1pct"]),

    dict(id="s1-1", src="seido1p", start=0.0, end=22.90, poster=9.2, rank="1",
         title="早めると減る・遅らせると増える", when="年金をもらい始めるとき", who=["nenkin"],
         point="1か月早めるごとに0.4%減（60歳なら24%減）。1か月遅らせるごとに0.7%増（75歳なら84%増）。",
         todo="", items=[]),
    dict(id="s1-2", src="seido1p", start=23.10, end=31.70, poster=27.6, rank="2",
         title="65歳で月15万円なら、いくら？", when="年金をもらい始めるとき", who=["nenkin"],
         point="60歳からなら月11.4万円、75歳からなら月27.6万円（仮の計算）。一度決めたら一生そのまま。",
         todo="", items=[]),
    dict(id="s1-3", src="seido1p", start=32.06, end=46.47, poster=40.5, rank="3",
         title="もらった合計で比べると", when="年金をもらい始めるとき", who=["nenkin"],
         point="60歳開始は約80歳10か月で65歳開始に抜かれます。75歳開始が65歳開始を抜くのは約86歳11か月。",
         todo="", items=[]),
    dict(id="s1-4", src="seido1p", start=46.47, end=59.34, poster=51.8, rank="4",
         title="決める前に気をつけたいこと", when="年金をもらい始めるとき", who=["nenkin"],
         point="待つ間は加給年金がもらえません。早くもらう請求は取り消せません。正解は健康・貯金・働き方しだい。",
         todo="", items=[]),

    dict(id="s2-1", src="seido2p", start=0.0, end=14.90, poster=7.8, rank="5位・4位",
         title="年金額改定通知書・源泉徴収票", when="6月・1月に届く", who=["nenkin"],
         point="6月の通知書で、額と天引きを確かめる。1月の源泉徴収票は、確定申告で税金が戻る人も。",
         todo="捨てずに中身を確かめる", items=[]),
    dict(id="s2-2", src="seido2p", start=19.42, end=33.14, poster=22.6, rank="3位",
         title="公金受取口座の意向確認書", when="届いたら45日以内", who=["nenkin"],
         point="受け取って45日、何もしないと年金の口座が公金受取口座に登録されます。困らない人も多いけれど、嫌なら返送。",
         todo="嫌なら45日以内に返送", items=[]),
    dict(id="s2-3", src="seido2p", start=33.14, end=44.34, poster=36.2, rank="2位",
         title="扶養親族等申告書", when="秋に届く", who=["nenkin"],
         point="出さないと、控除の分だけ税金が多く引かれます。出し忘れても確定申告で戻せます。",
         todo="期限は届いた書類で確かめて出す", items=[]),
    dict(id="s2-4", src="seido2p", start=44.34, end=58.10, poster=48.4, rank="1位",
         title="年金生活者支援給付金のはがき", when="届いたらすぐ", who=["nenkin"],
         point="基準額は月5,620円（2026年度）。案内の期限を過ぎると、さかのぼれない月が出ます。",
         todo="届いたはがき（請求書）を出す", items=["nenkin_shienkyufu"]),

    dict(id="s3-1", src="seido3p", start=0.0, end=18.58, poster=10.4, rank="1",
         title="9割戻る？介護保険の住宅改修", when="工事の前に", who=["kaigo"],
         point="要支援・要介護の人の家の、手すりや段差の工事が対象。上限は原則20万円、1割負担なら最大18万円が戻ります。",
         todo="", items=["kaigo_jutaku"]),
    dict(id="s3-2", src="seido3p", start=18.58, end=35.50, poster=26.4, rank="2",
         title="工事の前に申請する", when="工事の前に", who=["kaigo"],
         point="先に市区町村へ申請、工事はそのあと。申請前の工事は原則対象外で、全額自分で払うことになります。",
         todo="工事の前に市区町村へ申請", items=["kaigo_jutaku"]),
    dict(id="s3-3", src="seido3p", start=35.87, end=49.77, poster=38.4, rank="3",
         title="対象の工事と自己負担", when="工事の前に", who=["kaigo"],
         point="手すり・段差・滑りにくい床・引き戸・洋式トイレなど。自己負担は所得で1〜3割。まずケアマネジャーに相談。",
         todo="ケアマネジャーに相談（理由書も必要）", items=["kaigo_jutaku"]),
]
