#!/usr/bin/env python3
"""Veo などで作った動画クリップを Gemini に見せて、AI 特有の破綻がないか検査する（目で見る前のふるい）。

  PROJ=作品フォルダ python3 clip_check.py work/clips_try/*.mp4      → work/clipcheck.json と一覧画像 work/clipcheck_<ID>.jpg

見るところ：物が増える・消える・形が変わる（実例：手に持ったおもちゃの車が0.6秒で2台に）、顔・手の崩れ、
文字やロゴが現れる、カメラが勝手に動く、人数が変わる。最初の3秒で起きることが多いので、一覧画像は前半を細かく抜く。
判定は目安。最後は一覧画像を Read で見て、自分で決める。
"""
import json, os, subprocess, sys
from concurrent.futures import ThreadPoolExecutor
from PIL import Image, ImageDraw
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.environ.get("PROJ") or os.getcwd()
clips = [c for c in sys.argv[1:] if c.endswith(".mp4")]
if not clips: sys.exit(__doc__)
work = os.path.join(ROOT, "work"); os.makedirs(work, exist_ok=True)
prompt = os.path.join(work, "p_clipcheck.txt")
open(prompt, "w", encoding="utf-8").write(
    "This short clip was generated by an image-to-video AI from a still photo. Watch it closely, especially the first 3 seconds, and answer ONLY in JSON:\n"
    '{"objects_added_or_duplicated": [things that appear, multiply or vanish, with the time], '
    '"shape_changes": [objects or bodies that warp, melt or morph], "faces_distorted": true/false, "hands_distorted": true/false, '
    '"text_or_logos_appear": true/false, "camera_moves": "none" | "slight" | "large", "people_count_changes": true/false, '
    '"motion_quality": "natural" | "slightly odd" | "unnatural", "severity": "none" | "minor" | "major", "notes": "one short sentence"}\n'
    "major = a viewer would clearly notice something wrong.")
TIMES = (0.2, 0.6, 1.0, 1.6, 2.4, 3.5, 5.0, 7.6)

def sheet(clip, sid):
    tiles = []
    for t in TIMES:
        f = os.path.join(work, f"_cc_{sid}_{t}.jpg")
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-ss", str(t), "-i", clip, "-frames:v", "1", "-vf", "scale=480:270", f])
        if os.path.exists(f):
            im = Image.open(f).convert("RGB"); ImageDraw.Draw(im).text((6, 4), f"{sid} {t}s", fill=(255, 255, 0)); tiles.append(im); os.remove(f)
    sh = Image.new("RGB", (4 * 484, 2 * 274))
    for k, im in enumerate(tiles): sh.paste(im, ((k % 4) * 484, (k // 4) * 274))
    out = os.path.join(work, f"clipcheck_{sid}.jpg"); sh.save(out, quality=85); return out

def check(clip):
    sid = os.path.splitext(os.path.basename(clip))[0]
    sh = sheet(clip, sid)
    out = os.path.join(work, f"_cc_{sid}.json")
    for k in range(2):
        p = subprocess.run([sys.executable, os.path.join(HERE, "gem.py"), "--video", clip, "--prompt-file", prompt, "--out", out, "--json", "--think", "low"], capture_output=True, text=True)
        try:
            return sid, json.load(open(out)), sh
        except Exception:
            if "HTTP 402" in p.stdout: break
    return sid, {"error": (p.stdout + p.stderr)[:200]}, sh

path = os.path.join(work, "clipcheck.json")
res = json.load(open(path)) if os.path.exists(path) else {}
with ThreadPoolExecutor(4) as ex:
    for sid, r, sh in ex.map(check, clips):
        res[sid] = r
        print(sid, r.get("severity", "?"), "|", r.get("notes") or r.get("error", ""), "|", sh, flush=True)
json.dump(res, open(path, "w"), ensure_ascii=False, indent=1)
